<a href="https://colab.research.google.com/github/pbabvey/coding_brush_up/blob/master/NumPy_all_about.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Define Arrays

In [ ]:
import numpy as np
x = np.array([[12,3,4],[3,0,-1]])
x.ndim

2

In [ ]:
x = np.array([[5, 78, 2, 34, 0],
              [6, 79, 3, 35, 1],
              [7, 80, 4, 36, 2]])
x.ndim

2

In [ ]:
y=x.astype('float64')/80
y

array([[0.0625, 0.975 , 0.025 , 0.425 , 0.    ],
       [0.075 , 0.9875, 0.0375, 0.4375, 0.0125],
       [0.0875, 1.    , 0.05  , 0.45  , 0.025 ]])

### random arrays

In [ ]:
#multiply matrices
A = np.random.randint(5,size=(2,3))
B = np.random.randint(5,size=(3,2))
print(A)
print(B)
C = np.dot(A,B)
C

[[3 2 4]
 [1 2 1]]
[[2 1]
 [0 0]
 [0 2]]


array([[ 6, 11],
       [ 2,  3]])

In [ ]:
x = np.random.random(( 3, 2, 5))
y = np.random.random((2, 5))
z = np.maximum(x, y)
z

array([[[0.58585131, 0.98613745, 0.85398083, 0.8056581 , 0.63153706],
        [0.56911715, 0.62016268, 0.64092263, 0.29224701, 0.87642197]],

       [[0.4126968 , 0.65678298, 0.85398083, 0.87019307, 0.64119208],
        [0.82181541, 0.3662144 , 0.7445715 , 0.71956732, 0.87642197]],

       [[0.23889378, 0.79617226, 0.85398083, 0.8056581 , 0.68754194],
        [0.56911715, 0.3662144 , 0.65242453, 0.66863007, 0.87642197]]])

### empty 
create a matrix and arbitrary values for cells

In [ ]:
import numpy as np
A = np.empty(10)
A

array([2.6903171e-316, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
       0.0000000e+000, 0.0000000e+000, 0.0000000e+000, 0.0000000e+000,
       0.0000000e+000, 0.0000000e+000])

## subarray selection

In [ ]:
import numpy as np

a =  np.array([[1,2,3],[4,5,6]])
a[:,2]


array([3, 6])

# Transformations

### transformation, reshape

In [ ]:
# transpose and reshape
print(A)
print(np.transpose(A))
A.reshape((1,6))

[[3 2 4]
 [1 2 1]]
[[3 1]
 [2 2]
 [4 1]]


array([[3, 2, 4, 1, 2, 1]])

In [ ]:
import numpy as np
np.argmax([[1,2,5,9],[3,1,8,6]], axis=0)

array([1, 0, 1, 0])