<a href="https://colab.research.google.com/github/pbabvey/coding_brush_up/blob/master/TensorFlow_all_about.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Algabraic transformations

# Linear Algebra using TF

Lot's of useful information:
https://biswajitsahoo1111.github.io/post/doing-linear-algebra-using-tensorflow-2/ <br>
also the content are available in a Colab Notebook
I'm adding to it from other sources

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.6.0


In [ ]:
a = tf.constant(5.0)
print(a)
print(a.numpy())

tf.Tensor(5.0, shape=(), dtype=float32)
5.0


In [ ]:
a = tf.constant([1, 3, 7, 9]) 
print(a,'\n')
a = tf.constant([[1,2,3,4], [5,6,7,8]])
print(a,'\n') 
a = tf.constant([1,2,3,4,5,6,7,8.0], shape = (2,4))
print(a,'\n')
a = tf.constant(tf.range(1,13), shape = (2,3,2))
print(a,'\n')

tf.Tensor([1 3 7 9], shape=(4,), dtype=int32) 

tf.Tensor(
[[1 2 3 4]
 [5 6 7 8]], shape=(2, 4), dtype=int32) 

tf.Tensor(
[[1. 2. 3. 4.]
 [5. 6. 7. 8.]], shape=(2, 4), dtype=float32) 

tf.Tensor(
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]], shape=(2, 3, 2), dtype=int32) 



In [ ]:
import tensorflow as tf

b = tf.constant([1.,2,3])
x = b * 10
y = x + b
print(y)



tf.Tensor([11. 22. 33.], shape=(3,), dtype=float32)




### Creating a sequence of numbers

There are two ways to generate sequence of numbers in `Tensorflow`. Functions `tf.range` and `tf.linspace` can be used for that purpose. Sequences generated by these functions are equally spaced.

In [ ]:
seq = tf.range(start = 1,limit = 10, delta = 1)
print(seq.numpy())
seq = tf.range(start = 1, limit = 9, delta = 1.5)
print(seq.numpy())

[1 2 3 4 5 6 7 8 9]
[1.  2.5 4.  5.5 7.  8.5]


In [ ]:
tf.linspace(start = 1.0, stop = 10, num = 25)  # Start must be a `float`. 

<tf.Tensor: shape=(25,), dtype=float32, numpy=
array([ 1.   ,  1.375,  1.75 ,  2.125,  2.5  ,  2.875,  3.25 ,  3.625,
        4.   ,  4.375,  4.75 ,  5.125,  5.5  ,  5.875,  6.25 ,  6.625,
        7.   ,  7.375,  7.75 ,  8.125,  8.5  ,  8.875,  9.25 ,  9.625,
       10.   ], dtype=float32)>

## Slicing

In [ ]:
vector = tf.range(start = 1, limit = 10)
print(vector[3:7].numpy(), '\n')
matrix = tf.constant(tf.range(20, dtype = tf.float32), shape = (4,5))
print(matrix, '\n') 
print(matrix[1:3, 2:4],'\n')
print(matrix[:3,2:])

[4 5 6 7] 

tf.Tensor(
[[ 0.  1.  2.  3.  4.]
 [ 5.  6.  7.  8.  9.]
 [10. 11. 12. 13. 14.]
 [15. 16. 17. 18. 19.]], shape=(4, 5), dtype=float32) 

tf.Tensor(
[[ 7.  8.]
 [12. 13.]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[ 2.  3.  4.]
 [ 7.  8.  9.]
 [12. 13. 14.]], shape=(3, 3), dtype=float32)


## Modifying elements of a matrix

`Tensors` in `tensorflow`, once created, can't be modified. So the following code segment will result in an error.

```
>>> a = tf.constant([1,2,3,4])
>>> a[2] = 5  # Error
```

Instead of creating a `tensor`, we create a `Variable`. `Variables` work just like `tensors` with the added advantage that their values can be modified. So if we want to modify entries of our matrix at a later stage, we have to first create our matrix as a variable. 

In [ ]:
variable_mat = tf.Variable(tf.constant(tf.range(12, dtype = tf.float32), shape = (3,4)))

variable_mat[:2,2:4].assign(-1*tf.ones(shape = (2,2)))

variable_mat

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float32, numpy=
array([[ 0.,  1., -1., -1.],
       [ 4.,  5., -1., -1.],
       [ 8.,  9., 10., 11.]], dtype=float32)>

## Transpose of a matrix

For real matrices `transpose` just means changing the rows into columns and vice versa. There are three functions that achieve this.

* `tf.transpose`
* `tf.adjoint`
* `tf.matrix_transpose`

For real matrices, all three functions give identical results.

In [ ]:
matrix = tf.constant(tf.range(20, dtype = tf.float32), shape = (4,5))
matrix_tr = tf.transpose(matrix)
print(matrix_tr)

tf.Tensor(
[[ 0.  5. 10. 15.]
 [ 1.  6. 11. 16.]
 [ 2.  7. 12. 17.]
 [ 3.  8. 13. 18.]
 [ 4.  9. 14. 19.]], shape=(5, 4), dtype=float32)


In [ ]:
print(tf.linalg.adjoint(matrix))
print(tf.linalg.matrix_transpose(matrix))

tf.Tensor(
[[ 0.  5. 10. 15.]
 [ 1.  6. 11. 16.]
 [ 2.  7. 12. 17.]
 [ 3.  8. 13. 18.]
 [ 4.  9. 14. 19.]], shape=(5, 4), dtype=float32)
tf.Tensor(
[[ 0.  5. 10. 15.]
 [ 1.  6. 11. 16.]
 [ 2.  7. 12. 17.]
 [ 3.  8. 13. 18.]
 [ 4.  9. 14. 19.]], shape=(5, 4), dtype=float32)


## Some common matrices

In [ ]:
print(tf.zeros(shape = (3,5), dtype = tf.float32))
print(tf.ones(shape = (2,4), dtype = tf.float32))

tf.Tensor(
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]], shape=(3, 5), dtype=float32)
tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(2, 4), dtype=float32)


In [ ]:
print(tf.linalg.eye(5))
print(tf.linalg.diag([1.,2,3,4,5]))

tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]], shape=(5, 5), dtype=float32)
tf.Tensor(
[[1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]
 [0. 0. 0. 0. 5.]], shape=(5, 5), dtype=float32)


In [ ]:
print(tf.linalg.diag([1,2,3,4], k = 1))   # Values in super-diagonal
print(tf.linalg.diag([1,2,3], k = -2))   

tf.Tensor(
[[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]], shape=(5, 5), dtype=int32)
tf.Tensor(
[[0 0 0 0 0]
 [0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]], shape=(5, 5), dtype=int32)


In [ ]:
tf.linalg.diag([1,2,3,4,5], k = 0, padding_value = -1)

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[ 1, -1, -1, -1, -1],
       [-1,  2, -1, -1, -1],
       [-1, -1,  3, -1, -1],
       [-1, -1, -1,  4, -1],
       [-1, -1, -1, -1,  5]], dtype=int32)>

In [ ]:
mat = tf.zeros(shape = (5,5))
diag = tf.constant([1,2,3,4,5.])
tf.linalg.set_diag(input = mat, diagonal = diag, k = 0)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.],
       [0., 0., 0., 0., 5.]], dtype=float32)>

In [ ]:
diags = tf.constant([[1,2,3,4,5],
                     [6,7,8,9,0.]])
tf.linalg.set_diag(mat, diags, k = (-1,0))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [6., 2., 0., 0., 0.],
       [0., 7., 3., 0., 0.],
       [0., 0., 8., 4., 0.],
       [0., 0., 0., 9., 5.]], dtype=float32)>

## Random matrices
Rather, they are part of tf.random library. Using Tensorflow we can create matrices whose entries come from normal, uniform, poisson, and gamma distributions.

In [ ]:
# Random Uniform 
print(tf.random.uniform(shape = (5,5), minval = 0, maxval = 5, seed= 32))

tf.Tensor(
[[4.8578553  0.26324332 1.7549878  4.434555   2.3975224 ]
 [3.219039   0.4039365  0.92039883 2.9136662  4.9377174 ]
 [4.617196   3.6782126  4.0351195  4.8321657  4.206293  ]
 [2.3059547  4.922245   4.186061   2.1761923  0.88124394]
 [2.7422066  1.5948689  2.6099925  4.4901986  2.4033623 ]], shape=(5, 5), dtype=float32)


In [ ]:
# Random int
uniform_int = tf.random.uniform(shape = (5,5), minval= 10, maxval = 20, dtype = tf.int32, seed = 1234)
uniform_int

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[19, 15, 13, 14, 10],
       [16, 18, 10, 15, 10],
       [12, 13, 19, 12, 16],
       [18, 11, 10, 18, 12],
       [17, 18, 14, 19, 10]], dtype=int32)>

For further processing we usually require matrix entries to be floating point numbers. This can be achieved by using tf.cast.

In [ ]:
uniform_float = tf.dtypes.cast(uniform_int, dtype = tf.float32)
uniform_float

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[19., 15., 13., 14., 10.],
       [16., 18., 10., 15., 10.],
       [12., 13., 19., 12., 16.],
       [18., 11., 10., 18., 12.],
       [17., 18., 14., 19., 10.]], dtype=float32)>

In [ ]:
# Random Normal
normal_tf = tf.random.normal(shape = (5,5), mean = 1, stddev= 3, seed = 253)
normal_tf

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 1.5266892 , -5.114835  ,  4.4653835 , -1.013567  , -1.1874259 ],
       [ 5.503375  , -1.4568715 , -1.3270268 ,  0.2747649 ,  3.1374507 ],
       [ 4.211556  ,  4.618066  ,  1.2217634 ,  0.04707372,  1.4131291 ],
       [-2.7024255 ,  0.81293994, -3.11763   , -3.043394  ,  5.5663233 ],
       [ 1.4549919 ,  3.7368293 ,  1.2184538 ,  2.0713992 ,  0.19450545]],
      dtype=float32)>

In [ ]:
# Random Truncated Normal
tr_normal_tf = tf.random.truncated_normal(shape = (5,5), mean = 0, stddev= 2, seed = 82) 
tr_normal_tf

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 2.3130474 ,  1.9175851 ,  1.1134342 , -3.6221776 , -2.242488  ],
       [ 2.8108876 , -1.8440694 ,  1.7630143 , -0.45916542, -0.20763762],
       [-0.4769438 ,  2.3582413 , -0.45690525, -0.42088556, -1.8990422 ],
       [-2.2638845 ,  2.9536312 ,  0.9591611 ,  2.670887  ,  1.4793464 ],
       [-0.60492915,  3.6320126 ,  3.9752324 , -0.4684417 , -3.2791114 ]],
      dtype=float32)>

In [ ]:
# Random Poisson
poisson_tf = tf.random.poisson(shape = (5,5), lam = 2, seed = 12)
poisson_tf

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 1., 2., 3.],
       [0., 1., 2., 3., 4.],
       [2., 0., 2., 2., 2.],
       [2., 0., 2., 2., 3.],
       [1., 4., 2., 5., 4.]], dtype=float32)>

In [ ]:
# Random Gamma
gamma_tf = tf.random.gamma(shape = (5,5), alpha = 0.7, beta= 0.3, seed = 232)
gamma_tf

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[0.78733766, 2.5200539 , 0.9812998 , 5.141082  , 1.9184761 ],
       [1.1069427 , 0.32923967, 0.13172682, 5.066955  , 2.8487072 ],
       [0.39204285, 0.53647757, 5.3083944 , 1.618826  , 0.41352856],
       [1.0327125 , 0.27330002, 0.34577194, 0.22123706, 0.77021873],
       [0.38616025, 9.153643  , 1.4737413 , 6.029133  , 0.05517024]],
      dtype=float32)>

## Sparse matrices

Sparse matrices are within `tf.sparse` library. There are several functions specifically designed for sparse matrices. Full list of function in `tf.sparse` library can be found at [this link](https://www.tensorflow.org/api_docs/python/tf/sparse). The first argument is set of indices (rows and columns), second argument is the values at those indices. Third argument is the `dense_shape` of the sparse matrix.

In [ ]:
sparse_mat = tf.sparse.SparseTensor([[0,1],[1,3],[3,2]], [-5, -10, 7], dense_shape= (5,5))
sparse_mat

To see the actual matrix, we have to convert the sparse matrix to a dense matrix. This is achieved using `to_dense` function.

In [ ]:
tf.sparse.to_dense(sparse_mat)

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[  0,  -5,   0,   0,   0],
       [  0,   0,   0, -10,   0],
       [  0,   0,   0,   0,   0],
       [  0,   0,   7,   0,   0],
       [  0,   0,   0,   0,   0]], dtype=int32)>

It should be noted that special algorithms exist to deal with sparse matrices. Those algorithms don't require the sparse matrix to be converted into its dense equivalent. By converting a sparse matrix into a dense one, all its special properties are lost. Therefore, sparse matrices should not be converted into dense ones.

## Matrix multiplication

To multiply two vectors, or two matrices, or a matrix with a vector in a linear algebra sense, we have to use `linalg.matmul` function. Using `*` operator in python does element wise multiplication with broadcasting wherever possible. So to multiply two matrices, we have to call `linalg.matmul` function. Inputs to `linalg.matmul` function are matrices. Therefore, while multiplying two arrays, we have to first convert them into vectors and then multiply. Also note that `linalg.matmul` is same as `tf.matmul`. Both are aliases.

### Vectors

In [ ]:
vector_1 = tf.constant([1., 2., 3.], shape = (3,1))
vector_2 = tf.constant([2., 3., 4.], shape = (3,1))
result = tf.matmul(a = vector_1, b = vector_2, transpose_a = True) # Inner product
result.numpy()

array([[20.]], dtype=float32)

In [ ]:
vector_1 = tf.constant([1., 2., 3.], shape = (3,1))
vector_2 = tf.constant([2., 3., 4.], shape = (3,1))
result = tf.matmul(a = vector_1, b = vector_2, transpose_b = True) # Outer product
result.numpy()

array([[ 2.,  3.,  4.],
       [ 4.,  6.,  8.],
       [ 6.,  9., 12.]], dtype=float32)

#### Multiplying a matrix with a vector

There are two ways in which we can achieve this. We can convert the vector into a column vector (matrix with 1 column) and then apply `tf.matmul`, or we can use the built-in function `tf.linalg.matvec` to multiply a matrix with a vector.

In [ ]:
vector_1 = tf.constant([1., 2., 3.], shape = (3,1))
mat_1 = tf.constant([1, 2, 3, 4, 5, 6],shape = (2,3), dtype = tf.float32)
print( mat_1.numpy() )
tf.matmul(a = mat_1, b = vector_1).numpy()

[[1. 2. 3.]
 [4. 5. 6.]]


array([[14.],
       [32.]], dtype=float32)

In [ ]:
# another way, not prefered
tf.linalg.matvec(mat_1, tf.constant([1,2,3.])) 

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([14., 32.], dtype=float32)>

In [ ]:
mat = tf.constant([1, 2, 3, 4, 5, 6],shape = (2,3), dtype = tf.float32)
tf.linalg.matmul(a = mat, b = mat, transpose_a=True).numpy() # Without `transpose_a` argument, result will be an error.

array([[17., 22., 27.],
       [22., 29., 36.],
       [27., 36., 45.]], dtype=float32)

In [ ]:
mat = tf.constant([1, 2, 3, 4, 5, 6],shape = (2,3), dtype = tf.float32)
tf.linalg.matmul(a = mat, b = mat, transpose_b=True).numpy()

array([[14., 32.],
       [32., 77.]], dtype=float32)

In [ ]:
import tensorflow as tf
x= tf.constant(([1., 2, 3, 4]))
y = tf.math.multiply(x, x)
y

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 1.,  4.,  9., 16.], dtype=float32)>

In [ ]:
tf.reduce_mean(y)
tf.math.sqrt(tf.reduce_mean(5* y))

<tf.Tensor: shape=(), dtype=float32, numpy=6.1237245>

Generate tensors

#optimization

https://stackoverflow.com/questions/41918795/minimize-a-function-of-one-variable-in-tensorflow

In [ ]:
import tensorflow as tf
from tensorflow.python.training import gradient_descent

x = tf.Variable(10.0, trainable=True)
y = tf.Variable(5.0, trainable=True)




for i in range(10000):
    if i % 1000 == 0:
        z = tf.constant(i/100+1, dtype = 'float32')
        t = x + 2
        @tf.function
        def f_x():
            return (t - y)**2 + (x - z)**2
        print([x.numpy(), y.numpy(), z.numpy(), f_x().numpy()])
    gradient_descent.GradientDescentOptimizer(0.1).minimize(f_x)

[10.0, 5.0, 1.0, 130.0]
[1.0000002, 11.999998, 11.0, 180.99997]
[10.999998, 3.0000007, 21.0, 199.99998]
[20.999996, 12.999996, 31.0, 200.00008]
[30.999996, 22.999992, 41.0, 200.00015]
[40.999992, 32.99999, 51.0, 200.00023]
[50.999992, 42.999985, 61.0, 200.0003]
[60.999992, 52.999985, 71.0, 200.0003]
[70.999985, 62.999985, 81.0, 200.0003]
[80.999985, 72.99997, 91.0, 200.00061]


In [ ]:
x

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=90.999985>

A complete example
https://www.tensorflow.org/guide/keras/writing_a_training_loop_from_scratch

In [ ]:
x = tf.constant([0., 1., 0., 0.]) 
y = tf.constant([-2., 0., 2., 5.]) 
tf.math.maximum(x, y)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0., 1., 2., 5.], dtype=float32)>

In [ ]:
import tensorflow as tf
X = tf.constant([1.,2.,3])
tf.nn.softmax(X)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0.09003057, 0.24472848, 0.66524094], dtype=float32)>

In [ ]:
indices = [0, 1, 2]
depth = 3
tf.one_hot(indices, depth)  # output: [3 x 3]
# [[1., 0., 0.],
#  [0., 1., 0.],
#  [0., 0., 1.]]

NameError: ignored

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


In [ ]:
import numpy as np

train_images = np.load(open('gdrive/My Drive/Colab Notebooks/TDI/datacourse/tensorflow/\
miniprojects/train_images.npy', 'rb'))
train_labels = np.load(open('gdrive/My Drive/Colab Notebooks/TDI/datacourse/tensorflow/\
miniprojects/train_labels.npy', 'rb'))
validation_images = np.load(open('gdrive/My Drive/Colab Notebooks/TDI/datacourse/tensorflow/\
miniprojects/validation_images.npy', 'rb'))

In [ ]:
import tensorflow as tf
from tensorflow.keras import layers
from tensorflow.keras import models
from tensorflow.keras.layers import Lambda
from tensorflow.image import ResizeMethod

# include_top=False will discard avg_pool before prediction layer
inception = tf.keras.applications.inception_v3.InceptionV3(include_top=True, input_shape=(299, 299, 3))
inception = tf.keras.Model([inception.input], [inception.layers[-2].output]) # manually discard prediction layer

96116736/96112376 [==============================] - 1s 0us/step


In [ ]:
model = models.Sequential()
model.add(Lambda(lambda inputs:tf.image.resize(inputs, (299,299), 
                                               method=ResizeMethod.BILINEAR, preserve_aspect_ratio=False), input_shape = (32,32,3)))
model.add(inception)
model.add(layers.Dense(512, activation = 'relu'))
model.add(layers.Dense(10, activation = 'softmax'))

In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lambda (Lambda)              (None, 299, 299, 3)       0         
_________________________________________________________________
functional_1 (Functional)    (None, 2048)              21802784  
_________________________________________________________________
dense (Dense)                (None, 512)               1049088   
_________________________________________________________________
dense_1 (Dense)              (None, 10)                5130      
Total params: 22,857,002
Trainable params: 22,822,570
Non-trainable params: 34,432
_________________________________________________________________


In [ ]:
from tensorflow.keras.utils import to_categorical

train_labels_cat = to_categorical(train_labels)

optimizer = tf.keras.optimizers.Adam(
    learning_rate=1, beta_1=0.9, beta_2=0.999, epsilon=1e-07, amsgrad=False,
    name='Adam')
model.compile(optimizer='Adam', 
             loss = 'categorical_crossentropy',
             metrics = 'accuracy')

model.fit(train_images, train_labels_cat, epochs = 1, batch_size = 32)

1563/1563 [==============================] - 366s 234ms/step - loss: 0.2897 - accuracy: 0.9019


In [ ]:
preds = model.predict(validation_images)

In [ ]:
predicted_classes = [np.argmax(pred) for pred in preds]
#predicted_classes

In [ ]:
np.save('result', predicted_classes)

# TF.V1

take a look at this [response](https://stackoverflow.com/questions/55142951/tensorflow-2-0-attributeerror-module-tensorflow-has-no-attribute-session) 
